name: Rotate Twitter OAuth2 token

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

concurrency:
  group: twitter-token-rotation
  cancel-in-progress: false

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Refresh Twitter tokens
        env:
          TWITTER_CLIENT_ID: ${{ secrets.TWITTER_CLIENT_ID }}
          TWITTER_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENT_SECRET }}
          TWITTER_OAUTH2_REFRESH_TOKEN: ${{ secrets.TWITTER_OAUTH2_REFRESH_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: bash scripts/ci/refresh_twitter_token.sh
